apiVersion: v1
kind: Service
metadata:
  namespace: cs3219
  name: cs3219-db
  labels:
    app: cs3219-db
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: cs3219-db
