apiVersion: v1
kind: Service
metadata:
  namespace: cs3219
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: order-service
