apiVersion: v1
kind: Service
metadata:
  namespace: cs3219
  name: api-gateway
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: order-service